version: '3.4'
services:
    app:
        build:
            context: ./app
            target: builder
            args:
                environment: development
        environment:
            - DB_USER=${DB_USER}
            - DB_PW=${DB_PW}
            - DB_NAME=${DB_NAME}
            - DB_PORT=${DB_PORT}
            - DB_HOST=${DB_HOST}
            - MAX_DB_CONNECTIONS=${MAX_DB_CONNECTIONS}
        volumes:
            - ./app:/app
        ports:
            - "80:80"
        links:
            - postgis
        depends_on:
            - postgis

volumes:
    pg_data:
