version: '3.4'
services:
    postgis:
        image: postgis/postgis
        container_name: postgis
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PW}
            - DB_NAME=${DB_NAME}
            - ALLOW_IP_RANGE=0.0.0.0/0
        ports:
            - '5432:5432'
        volumes:
            - 'pg_data:/var/lib/postgresql'
            - ./migration/bin/init/init.sh:/docker-entrypoint-initdb.d/init.sh
        restart: always
    flyway:
        image: flyway/flyway
        # postgres url schema: jdbc:postgresql://host:port/database
        command: -url=jdbc:postgresql://postgis:${DB_PORT}/${DB_NAME} -user=${DB_USER} -password=${DB_PW} -connectRetries=10 migrate info
        volumes:
            - ./migration/sql:/flyway/sql
        links:
            - postgis
        depends_on:
            - postgis
    app:
        environment:
            - DB_USER=${DB_USER}
            - DB_PW=${DB_PW}
            - DB_NAME=${DB_NAME}
            - DB_PORT=${DB_PORT}
            - DB_HOST=${DB_HOST}
            - MAX_DB_CONNECTIONS=${MAX_DB_CONNECTIONS}
            - WAIT_HOSTS=postgis:5432
        build:
            context: ./
            target: prod
            args:
                environment: production
        volumes:
            - ./app/:/go/src/app
        ports:
            - "80:80"
        links:
            - postgis
        depends_on:
            - postgis
        command: sh -c "/wait && /breadcrumbs"

volumes:
    pg_data:
